version: '3.9'

services:
  db:
    image: mysql:5.7
    volumes:
      - sandy_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - wp_network
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

  wordpress:
    image: wordpress
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - wp_network
    restart: always
    volumes:
      - wordpressone_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress

volumes:
  sandy_data:
  wordpressone_data:

networks:
  wp_network:

